---
- name: restart mysql
  sudo: yes
  service: name=mysqld state=restarted

- name: restart nginx
  sudo: yes
  service: name=nginx state=restarted

- name: start php-fpm
  sudo: yes
  service: name=php-fpm state=started
