---
- name : Install PHP
  sudo: yes
  yum: pkg={{ item }} state=present
  with_items:
    - php-fpm
    - php-mysql

- name : Configure php-fpm in php.ini
  sudo: yes
  copy: src=php.ini dest=/etc/
  notify: start php-fpm

- name : Configure php-fpm www.conf
  sudo: yes
  copy: src=www.conf dest=/etc/php-fpm.d/
  notify: restart php-fpm
