---
- name: Installs nginx web server
  sudo: yes
  yum: pkg=nginx state=present

- name: Start Nginx
  sudo: yes
  service: name=nginx state=started enabled=yes

- name: Copy nginx configuration for wordpress
  sudo: yes
  copy: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
